### ISSUE TITLE
Net:: err_file_not_found

### ISSUE THREAD

**Issue by boneq** [odranoelBR/vue-quasar-admin-example#13]
How is it configured on your server? How did I appear? Net:: err_file_not_found

**Comment by boneq** [comment]
I'm not doing app development, I was doing web development.
Web is always on the wrong side. I don't think your demo is wrong

**Comment by boneq** [comment]
cordova.js not found

**Comment by odranoelBR** [comment]
HI man. Tks for feedback
Can you show me a picture  ? 
When it happens ?

**Comment by odranoelBR** [comment]
Closing due to no response.
