### ISSUE TITLE
Router is not working.

### ISSUE THREAD

**Issue by deyangupta** [odranoelBR/vue-quasar-admin-example#15]
Most of the route is not working, if you paste URL into the browser address bar.
even page not found is not coming, after going to URL:
 https://quasar-admin.firebaseapp.com/pagenotfoundWord.

**Comment by odranoelBR** [comment]
Hi man. Tks

Try https://quasar-admin.firebaseapp.com/#/ < whit hashbang
Read: https://router.vuejs.org/en/essentials/history-mode.html
