### ISSUE TITLE
Plans to update to Quasar 0.14?

### ISSUE THREAD

**Issue by trsiddiqui** [odranoelBR/vue-quasar-admin-example#16]
Just wanted to know if you had any plans upgrading to Quasar 0.14 in the near future?

**Comment by odranoelBR** [comment]
Sure, .14 is awesome.
Working https://github.com/odranoelBR/vue-quasar-admin-example/tree/feature/Feature-migration-v.14

Tks \o/

**Comment by trsiddiqui** [comment]
I am getting an error while doing npm install 

No matching version found for up,js"?1.8.2

**Comment by trsiddiqui** [comment]
On replacing it with countup it works, but on running npm run dev after that gives the following error and wont build.

**Cannot find module `purify-css` at build\css-utils.js:4:12.**

**Comment by trsiddiqui** [comment]
Never mind, I fixed the issues in package.json and the pages and running the admin on 0.14 now :smile:

**Comment by odranoelBR** [comment]
Cool man, hope you like quasar .14. 
Tks for feedbacks

**Comment by paulvanbladel** [comment]
settings and profile are not found:

* ./settings in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/views/dashboard/one/dashboard.vue
* ./profile in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/views/dashboard/one/dashboard.vue

**Comment by trsiddiqui** [comment]
I just removed these references to run it
