### ISSUE TITLE
erro import

### ISSUE THREAD

**Issue by verdade** [odranoelBR/vue-quasar-admin-example#18]
Bom dia mano, parabéns pelo repositorio... Uma dúvida a partir dele tento importar elementos do quasar mais da o erro abaixo

<q-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by odranoelBR** [comment]
Obrigado brother! 
Então, o repositorio está em fase de migração para a versão 0.14+ do quasar ( que precisa importar manualmente cada componente quasar )

Para utilizar essa versão do branch master tem que setar no teu package.json a versão do quasar para 0.13

Abcs

**Comment by verdade** [comment]
Me perdoe a ignorância no momento, é que sou iniciante no vue e vou tocar um grande projeto com o vue + quasar e se Deus quiser com o seu template que ta show,  mas ainda não funciona.  Exemplo: quando declaro um "q-btn" etc... dá o erro abaixo, sendo que no meu package.json está "quasar-framework": "^0.13.2".  Você quiz dizer que no 0.14 é que vai precisar importar cada componente? Blz, então na versão "^0.13.2" eu somente incluí um <q-btn> e deu o erro abaixo, e não fiz o import do QBtn

Unknown custom element: "q-btn" - did you register the component correctly?

**Comment by verdade** [comment]
Eu entendi brow, vi seu branch 0.14, já pode usar ele?

**Comment by odranoelBR** [comment]
Ainda nao terminei de migrar tudo, mas pode utilizar sim. abcs
