### ISSUE TITLE
oauth2 authentication

### ISSUE THREAD

**Issue by ghost** [odranoelBR/vue-quasar-admin-example#21]
good morning, sorry for my horrible english.
i would like to learn vue and quasar, your project it's a very good start point.

i would like to implement to your admin-example the oauth2 authentication. what package do you suggest?

**Comment by odranoelBR** [comment]
Hi man!
I never used oauth2 with vuejs. 
Maybe your backend oauth system has some SDK javascript . This helps.

If not look this https://github.com/oauth-io/oauth-js

\o/
