### ISSUE TITLE
vue-i18n not working for all components exemple q-data-table

### ISSUE THREAD

**Issue by ayoubyoub** [odranoelBR/vue-quasar-admin-example#22]
Hello,
currently I use your beautiful template, on the other hand I have a problem at the internationalization using vue-i18n.
My label in french his name is : Rechercher but in the placeholder of my input always stays search using {{ $t('label.search')}} 
![image](https://user-images.githubusercontent.com/10756142/42728779-bfa0407e-87ba-11e8-91ba-5845b944d6e5.png)
Can you help plz ?
Merci, thank's

**Comment by odranoelBR** [comment]
Hi @ORAPLUS 
Can you show this code ? 

tks
