### ISSUE TITLE
how can i add q-field or q-input in the template

### ISSUE THREAD

**Issue by ayoubyoub** [odranoelBR/vue-quasar-admin-example#23]
Hello,
Can you plz help us, how we can add the components not existing in your template like q-field or q-input ?
I have this message error : 
![image](https://user-images.githubusercontent.com/10756142/42729175-af4fef64-87c7-11e8-95b4-d029d1bfbc0a.png)
Thank you

**Comment by odranoelBR** [comment]
Hi @ORAPLUS 
This template is outdated, in quasar version .13 ( all componentes are included) 

You probaly using a new version quasar ( 14+ )
Take a look at https://quasar-framework.org/components/introduction-for-beginners.html#Using-Quasar-Components

Newers versions must declare the component in quasar.conf.js

Tks
