### ISSUE TITLE
Admin example just won't build using Quasar 0.17.23

### ISSUE THREAD

**Issue by haiitch** [odranoelBR/vue-quasar-admin-example#25]
Going back to an older version is not an option in my case, because I have projects that depend on the current version of Quasar, and it wouldn't be a good idea anyway to write code in a style that's already deprecated.

Output follows:

haitch@lbox:~/proj/vue-quasar-admin-example$ quasar build
 app:paths ⚠️  Error. This command must be executed inside a Quasar v0.15+ project folder. +0ms
 app:paths For Quasar pre v0.15 projects, npm uninstall -g quasar-cli; npm i -g quasar-cli@0.6.5 +9ms

haitch@lbox:~/proj/vue-quasar-admin-example$ quasar --version
0.17.23

**Comment by odranoelBR** [comment]
Hi @htrob . Srr for the long time.
This repository is build in quasar .14, i know there's a lot of change from .17.
I'm planning to update here when  quasar 1.0 is arrive, its on beta now, so i thing theres is no much to wait.

**Comment by haiitch** [comment]
Quasar 1.0 beta is go  :+1:

**Comment by kosirm** [comment]
Looking forward to see branch feature/migration_v1 released! Thank you for this excellent example!

**Comment by odranoelBR** [comment]
Srr being late on answer. Hope it help and quassar keep growing. I will release this update soon.
________________________________
De: Milan Košir <notifications@github.com>
Enviado: quarta-feira, 16 de outubro de 2019 12:53
Para: odranoelBR/vue-quasar-admin-example <vue-quasar-admin-example@noreply.github.com>
Cc: Leonardo <odranoelo_O@hotmail.com>; State change <state_change@noreply.github.com>
Assunto: Re: [odranoelBR/vue-quasar-admin-example] Admin example just won't build using Quasar 0.17.23 (#25)


Looking forward to see branch feature/migration_v1 released! Thank you for this excellent example!

**Comment by haiitch** [comment]
Thanks guys!
