### ISSUE TITLE
Layout disappears when navigating back from login route

### ISSUE THREAD

**Issue by vishco** [odranoelBR/vue-quasar-admin-example#3]
I noticed that the layout is lost when I hit the back button on the browser from the login page. Just wanted to let you know.

Steps:
1) Go to '/login-one'
2) Click back the back button on the browser.

You will notice that the navigation bar and sidebar are no longer present.

**Comment by odranoelBR** [comment]
Tks a lot man. 
Im fixing!

**Comment by odranoelBR** [comment]
Fixed: bb8b35acdd93d9b4980f19593b311c3290985006

**Comment by vishco** [comment]
I just updated the project and the problem is still there.

**Comment by odranoelBR** [comment]
@vispatel Srr dude, I cannot reproduce this bug now.
Please check if the behavior is the same as the video
![quasar-admin-gif-bug](https://cloud.githubusercontent.com/assets/7774534/24430633/f18feac2-13ed-11e7-8ea2-90e971758e46.gif)

**Comment by vishco** [comment]
Maybe I'm doing something different, I've recorded a video to show you the problem.
https://drive.google.com/file/d/0B_t-DBKVOnxoN3Y0Nk5fQl9lZE0/view

**Comment by LarryEitel** [comment]
I can attest to similar behavior.

**Comment by odranoelBR** [comment]
Tks a lot guys.
This behavior are happening before bb8b35a.
Btw im reopening issue and looking into.

**Comment by odranoelBR** [comment]
@vispatel and @LarryEitel 
I did a fresh clone on differente machine (env) and tested in : 
- 56.0.2924.87 (64-bit)
- 52.0.1 (32-bit)
Working OK

Can you guys tell me what browser / version using ?
Tks

**Comment by vishco** [comment]
I'm able to replicate on my iPhone too using chrome and safari. On OSX the version of chrome is: 56.0.2924.87 (64-bit)

There is no need to clone a fresh version of the project, you can reproduce using the version you have on firebase. https://quasar-admin.firebaseapp.com/#/

Remember all you have to do is use the browser back button when on the login page. 

Thanks again.

**Comment by odranoelBR** [comment]
I was out of attention :)

I hope now we fixed.

**Comment by vishco** [comment]
Seems fine now, thanks a lot.
