### ISSUE TITLE
What is @input.right supposed to do in cardTodo.vue?

### ISSUE THREAD

**Issue by paulvanbladel** [odranoelBR/vue-quasar-admin-example#4]
Hi,
Very nice sample. Thanks for sharing.
What is @input.right supposed to do in cardTodo.vue?
I don't see how this is triggered?
```
    <input v-show="!todo.completed" v-model="todo.title" class="fit" @input.right="changeTitle(todo)">
```

**Comment by odranoelBR** [comment]
Sorry man, I really do not know what it does there.
I looked at the documentation and found nothing like it. It's a mistake. 

I wanted to make a lazy effect on change, so the change on backend/api is not triggered every keydown.

v-model.lazy + @change does what i need.
Tks a lot for the feedback!!!!

Fix : 5aa662e8c266d6bd6a29fdd420ede0e519a2cbf8
