### ISSUE TITLE
Any idea how to augment typescript with $http extension on Vue

### ISSUE THREAD

**Issue by paulvanbladel** [odranoelBR/vue-quasar-admin-example#5]
You apply a very smart approach for extending the generic vue instance with an $http class.

```
export default (Vue) => {
  Object.defineProperties(Vue.prototype, {
    $http: {
      get () {
        return axiosInstance
      }
    }
  })
}
```

I'm using typescript and obviously typescript isn't aware of the type augmentation.

Of course I could use is as follows: (<any>this).$http ... , but that's that's not so nice.
Do you have any idea how to augment the typescript definition in such a way this is digested correctly?

**Comment by odranoelBR** [comment]
Hi @paulvanbladel 
I just got  this great idea from https://github.com/codecasts/spa-starter-kit/blob/develop/client/src/plugins/http/index.js

I never used typescript, so i can't help you. 
BTW i will tell https://github.com/vinicius73, the autor of this code and he probaly can.

Tks !

**Comment by paulvanbladel** [comment]
Thanks a lot.

**Comment by paulvanbladel** [comment]
as follows: in a separate .d.ts file:

```
import {AxiosStatic} from 'axios';
declare module 'vue/types/vue' {
  export interface Vue   {
    $http: AxiosStatic;
  }
}
```

**Comment by odranoelBR** [comment]
Oh tks alot man!
