### ISSUE TITLE
how to set mobile mode ?

### ISSUE THREAD

**Issue by dev-chriss** [odranoelBR/vue-quasar-admin-example#6]
Hi,

I try your application, and u do great job.

but now im stuck how to show mobile mode on the browser like you do. 
would you give tutorial link how i can achieve that ?

thnx

**Comment by odranoelBR** [comment]
Hi man.
Thanks a lot, i hope it help you and community.

See if this video helps you, at the top left of the page is a smartphone to enter in mobile mode

![quasar-admin-mobile-mode](https://cloud.githubusercontent.com/assets/7774534/24749359/25e7b3ca-1a99-11e7-9bb8-e8bb1a069af5.gif)

**Comment by odranoelBR** [comment]
It helped you @chrissetyawan  ?

**Comment by dev-chriss** [comment]
no, but thnx for reply.. 
mobile mode is doesn't work on my localhost, i want to refer my own website when do mobile mode.

**Comment by odranoelBR** [comment]
I understand now, the mobile mode is an iframe poiting to quasar admin url.
 If u change it to your localhost adress, works.
